version: "3"

services:
  airsonic:
    container_name: airsonic
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    image: airsonic/airsonic:10.5.0-RELEASE
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.custom.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.custom.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.custom.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.custom.headers.frameDeny=true"
      - "traefik.http.middlewares.custom.headers.sslredirect=true"
      - "traefik.http.middlewares.custom.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.custom.headers.stsPreload=true"
      - "traefik.http.middlewares.custom.headers.stsSeconds=315360000"
      - "traefik.http.routers.airsonic.entrypoints=websecure"
      - "traefik.http.routers.airsonic.rule=Host(`airsonic.${DOMAIN_NAME}`)"
      - "traefik.http.routers.airsonic.tls.certresolver=letsencrypt"
    networks:
      - traefik_proxy
    ports:
      - 4040:4040
    restart: always
    volumes:
      - ./config:/config
      - /media/nas/Audiobooks:/airsonic/audiobooks
      - /media/nas/Music:/airsonic/music
      - /media/nas/Podcasts:/airsonic/podcasts
      - ./playlists:/airsonic/playlists

networks:
  traefik_proxy:
    external: true
